pybo/models.py
from pybo import db

class Recycle(db.Model):
    item = db.Column(db.String(100), primary_key=True)
    division = db.Column(db.String(100), nullable=False)
    exhaust = db.Column(db.String(300), nullable=False)

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    modify_date = db.Column(db.DateTime(), nullable=True)

class Answer(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set'))
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    modify_date = db.Column(db.DateTime(), nullable=True)

pybo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired

class QuestionForm(FlaskForm):
    subject = StringField('제목', validators=[DataRequired()])
    content = TextAreaField('내용', validators=[DataRequired()])

pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)

    from . import models

    from .views import main_views, recycle_views, question_views, answer_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(recycle_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)

    # 필터
    from .filter import format_datetime
    app.jinja_env.filters['datetime'] = format_datetime

    return app

pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    question = Question.query.get_or_404(question_id)
    content = request.form['content']
    answer = Answer(content=content, create_date=datetime.now())
    question.answer_set.append(answer)
    db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=answer.question.id))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', answer=answer, form=form)


@bp.route('/delete/<int:answer_id>')
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

from pybo.models import Recycle

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'Hello, Pybo'

@bp.route('/')
def index():
    return redirect(url_for('recycle._main'))

@bp.route('/list')
def list():
    return redirect(url_for('recycle._list'))


@bp.route('/question')
def question():
    return redirect(url_for('question._list'))

pybo/views/question_views.py
from flask import Blueprint, render_template, request, url_for

from pybo.models import Question
from ..forms import QuestionForm

from datetime import datetime

from werkzeug.utils import redirect
from .. import db

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)

@bp.route('detail/<int:question_id>/')
def detail(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question)

@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject = form.subject.data, content = form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()   #수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))

    else:
            form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/delete/<int:question_id>')
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/views/recycle_views.py
from flask import Blueprint, render_template, request

from pybo.models import Recycle
from pybo.models import Question
from .. import db

bp = Blueprint('recycle', __name__, url_prefix='/recycle')

@bp.route('/')
def _main():
    return render_template('recycle/recycle_main.html')

@bp.route('/list')
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    # 조회
    recycle_list = Recycle.query.order_by(Recycle.item.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        recycle_list = recycle_list.filter(Recycle.item.like(search) | Recycle.division.like(search))

    recycle_list = recycle_list.paginate(page, per_page=10)
    return render_template('recycle/recycle_list.html', recycle_list=recycle_list, page=page, kw=kw)

@bp.route('/search')
def search():
    kw = request.args.get('kw', type=str, default='')
    # 조회
    recycle_list = Recycle.query.order_by(Recycle.item.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        recycle_list = recycle_list.filter(Recycle.division.like(search))
    return render_template('recycle/search.html', recycle_list=recycle_list, kw=kw)

@bp.route('/paper')
def paper():
    return render_template('recycle/paper.html')

@bp.route('/can')
def can():
    return render_template('recycle/can.html')

@bp.route('/glass')
def glass():
    return render_template('recycle/glass.html')

@bp.route('/plastic')
def plastic():
    return render_template('recycle/plastic.html')

@bp.route('/vinyl')
def vinyl():
    return render_template('recycle/vinyl.html')

@bp.route('/styrofoam')
def styrofoam():
    return render_template('recycle/styrofoam.html')

pybo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RECYCLE</title>


  <!-- Bootstrap core CSS -->
  <link href="../../../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="../../../static/vendor/bootstrap/css/style.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="../../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../../../static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="../../../static/css/landing-page.min.css" rel="stylesheet">

</head>

<body>
{% block content %}
  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-sm bg-white navbar-white">
    <!-- Brand -->
    <div class="col-lg-4">
    <a class="navbar-brand" href="/"  style="padding-left: 50px;">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
    </a>
  </div>
    <!-- Links -->
    <ul class="navbar-nav">
      <!-- Dropdown -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          분리배출요령
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="paper">종이류, 종이팩</a>
          <a class="dropdown-item" href="can">금속캔, 고철</a>
          <a class="dropdown-item" href="glass">유리병류</a>
          <a class="dropdown-item" href="plastic">플라스틱 용기류</a>
          <a class="dropdown-item" href="vinyl">비닐류</a>
          <a class="dropdown-item" href="styrofoam">스티로폼(발포합성수지)</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="search" style="padding-left: 50px;">품목 검색</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="padding-left: 50px;">Q & A</a>
      </li>
    </ul>
  </nav>
{% endblock %}
</body>
</html>

pybo/templates/question/question_detail.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RECYCLE</title>


  <!-- Bootstrap core CSS -->
  <link href="../../../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="../../../static/vendor/bootstrap/css/style.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="../../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../../../static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="../../../static/css/landing-page.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-sm bg-white navbar-white">
    <!-- Brand -->
    <div class="col-lg-4">
    <a class="navbar-brand" href="/"  style="padding-left: 50px;">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
    </a>
  </div>
    <!-- Links -->
    <ul class="navbar-nav">
      <!-- Dropdown -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          분리배출요령
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="paper">종이류, 종이팩</a>
          <a class="dropdown-item" href="can">금속캔, 고철</a>
          <a class="dropdown-item" href="glass">유리병류</a>
          <a class="dropdown-item" href="plastic">플라스틱 용기류</a>
          <a class="dropdown-item" href="vinyl">비닐류</a>
          <a class="dropdown-item" href="styrofoam">스티로폼(발포합성수지)</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="search" style="padding-left: 50px;">품목 검색</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="padding-left: 50px;">Q & A</a>
      </li>
    </ul>
  </nav>
    <br><br><br><br>
  <div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
        <div class="d-flex justify-content-end">
          <div class="badge badge-light p-2">
            {{ question.create_date|datetime }}
          </div>
        </div>
        <!-- 수정 / 삭제 기능 -->
        <div class="my-3">
            <a href="{{ url_for('question.modify', question_id=question.id) }}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
        </div>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                  {{ answer.create_date|datetime }}
                </div>
            </div>
            <!-- 답변 수정 / 삭제 기능 -->
        <div class="my-3">
            <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
            data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
        </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

<script type='text/javascript'>
  $(document).ready(function(){
      $(".delete").on('click', function() {  // 클래스값이 delete인 엘리먼트가 눌리면?
          if(confirm("정말로 삭제하시겠습니까?")) {  // 확인 창이 열림
              location.href = $(this).data('uri');  // data-uri 속성값으로 URL 호출
          }
      });
  });
  </script>

</body>
</html>

pybo/templates/question/question_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}<!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-sm bg-white navbar-white">
    <!-- Brand -->
    <div class="col-lg-4">
    <a class="navbar-brand" href="/"  style="padding-left: 50px;">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
    </a>
  </div>
    <!-- Links -->
    <ul class="navbar-nav">
      <!-- Dropdown -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          분리배출요령
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="paper">종이류, 종이팩</a>
          <a class="dropdown-item" href="can">금속캔, 고철</a>
          <a class="dropdown-item" href="glass">유리병류</a>
          <a class="dropdown-item" href="plastic">플라스틱 용기류</a>
          <a class="dropdown-item" href="vinyl">비닐류</a>
          <a class="dropdown-item" href="styrofoam">스티로폼(발포합성수지)</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="search" style="padding-left: 50px;">품목 검색</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="padding-left: 50px;">Q & A</a>
      </li>
    </ul>
  </nav>
    <br><br><br><br>
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 수정</h5>
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}

        <!-- 오류표시 -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}
</body>
</html>

pybo/templates/question/question_list.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RECYCLE</title>


  <!-- Bootstrap core CSS -->
  <link href="../../../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="../../../static/vendor/bootstrap/css/style.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="../../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../../../static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="../../../static/css/landing-page.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-sm bg-white navbar-white">
    <!-- Brand -->
    <div class="col-lg-4">
    <a class="navbar-brand" href="/"  style="padding-left: 50px;">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
      <img src="../../../static/img/logoG.png" width="45px" height="40px">
    </a>
  </div>
    <!-- Links -->
    <ul class="navbar-nav">
      <!-- Dropdown -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          분리배출요령
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="paper">종이류, 종이팩</a>
          <a class="dropdown-item" href="can">금속캔, 고철</a>
          <a class="dropdown-item" href="glass">유리병류</a>
          <a class="dropdown-item" href="plastic">플라스틱 용기류</a>
          <a class="dropdown-item" href="vinyl">비닐류</a>
          <a class="dropdown-item" href="styrofoam">스티로폼(발포합성수지)</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="search" style="padding-left: 50px;">품목 검색</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="padding-left: 50px;">Q & A</a>
      </li>
    </ul>
  </nav>
    <br><br><br><br>
    <div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
                <td>
                    <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                    <!-- 답변  달린 갯수-->
                    {% if question.answer_set|length > 0 %}
                    <span class="text-danger small ml-2">{{ question.answer_set|length }}</span>
                    {% endif %}
                </td>
                <td>{{ question.create_date|datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if question_list.has_prev %}
      <li class="page-item">
          <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
      {% endif %}
      {% for page_num in question_list.iter_pages() %}
          {% if page_num %}
              {% if page_num != question_list.page %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
              </li>
              {% else %}
              <li class="page-item active" aria-current="page">
                  <a class="page-link" href="#">{{ page_num }}</a>
              </li>
              {% endif %}
         {% else %}
              <li class="disabled">
                  <a class="page-link" href="#">...</a>
              </li>
         {% endif %}
      {% endfor %}
      <!-- 다음페이지 -->
      {% if question_list.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
      {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
<!-- ---------------------------------------------------------------------- -->

        <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
    </div>
</body>
</html>

pybo/templates/recycle/can.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>RECYCLE</title>

  <!-- Bootstrap core CSS -->
  <link href="../../static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <link href="../../../static/vendor/bootstrap/css/style.css" rel="stylesheet">

  <!-- Custom fonts for this template -->

  <link href="../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="../../static/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
    type="text/css">

  <!-- Custom styles for this template -->
  <link href="../../static/css/landing-page.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-sm bg-white navbar-white">
    <!-- Brand -->
    <div class="col-lg-4">
    <a class="navbar-brand" href="/"  style="padding-left: 50px;">
      <img src="../../static/img/logoG.png" width="45px" height="40px">
      <img src="../../static/img/logoG.png" width="45px" height="40px">
    </a>
  </div>
    <!-- Links -->
    <ul class="navbar-nav">
      <!-- Dropdown -->

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          분리배출요령
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="paper">종이류, 종이팩</a>
          <a class="dropdown-item" href="can">금속캔, 고철</a>
          <a class="dropdown-item" href="glass">유리병류</a>
          <a class="dropdown-item" href="plastic">플라스틱 용기류</a>
          <a class="dropdown-item" href="vinyl">비닐류</a>
          <a class="dropdown-item" href="styrofoam">스티로폼(발포합성수지)</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="search" style="padding-left: 50px;">품목 검색</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" style="padding-left: 50px;">Q & A</a>
      </li>
    </ul>
  </nav>

  <!-- Image Showcases -->
  <section class="showcase">
    <div class="container-fluid p-0">
      <div class="row no-gutters">

        <div class="col-lg-6 order-lg-2 text-white showcase-img"
          style="background-image: url('../../static/img/rcan1.png');"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
          <h3>철캔, 알루미늄캔</h3>
          <h3>(음료, 주류캔, 식료품캔)</h3><br>
          <p class="lead mb-0">
            • 내용물을 비우고 물로 헹구는 등 이물질을 제거하여 배출합니다.<br><br>
            • 플라스틱 뚜껑 등 금속캔과 다른 재질은 제거한 후 배출합니다.

          </p>

        </div>
      </div>
      <div class="row no-gutters">
        <div class="col-lg-6 text-white showcase-img" style="background-image: url('../../static/img/rcan2.png');"></div>
        <div class="col-lg-6 my-auto showcase-text">
          <h3>고철(공기구, 철사, 못 등)</h3>
          <h3>비철금속(알미늄, 스텐류 등)</h3><br>
          <p class="lead mb-0">
            • 이물질이 섞이지 않도록 한 후 봉투에 넣거나 끈으로 묶어서 배출합니다.
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Bootstrap core JavaScript -->
  <script src="../../static/vendor/jquery/jquery.min.js"></script>
  <script src="../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>